# Generated by Django 6.0.1 on 2026-01-28 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='example',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='meaning',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.topic'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
